### ISSUE TITLE
PRUEBA TECNICA 14 de Marzo de 2024 - 15 de Marzo de 2024

### ISSUE THREAD

**Issue by galindocode** [Netsocs-Team/prueba-tecnica#1]
Buenos dias, en el sistema de issues pueden realizar cualquier consulta que tengan.

El tiempo para realizar el PR es hasta mañana 15 de marzo de 2024 hasta las 12:00 (mediodia)

**Comment by galindocode** [comment]
Buenos dias, si requiren algo mas de tiempo me puede comentar por aca y con gusto lo evaluamos.

**Comment by galu7777** [comment]
ok muchas gracias.

**Comment by ismaelxyz** [comment]
Requiero mas tiempo para terminar el segundo tab y su soporte en el backend, hacer las pruebas unitarias y además conectar el backend con el frontend

**Comment by galindocode** [comment]
Se extendera hasta manana a las 9am muchachos

**Comment by galu7777** [comment]
perfecto gracias.

**Comment by galindocode** [comment]
Buenos dias muchachos, es probable que falte por desarrollar algun punto y no se preocupen que lo entedemos perfectamente. Los invito a subir la prueba hasta donde se haya podido avanzar que con gusto la revisamos.

Repito, aunque la prueba no este completa al 100% no afecta en nada, igual se estara revisando los puntos que se desarrollaron

**Comment by galu7777** [comment]
Buenos días Leonardo, entonces actualizo el readme.md y hago push, gracias por la oportunidad agradecido con el equipo de Netsocs.

**Comment by ismaelxyz** [comment]
Buen día a todos, ¡Gracias al equipo de Netsocs  por su tiempo! 😊👍, ya envié mis cambios

**Comment by galindocode** [comment]
Buenos dias muchachos, muchas gracias por su participacion, estaremos revisando los proyectos y se le estaremos haciendo llegar la informacion por correo. Saludos a todos!
